// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration",              Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.Core.FMODSoundSystem.ChannelIsPlaying(System.UInt32)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration",              Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.Core.FMODSoundSystem.CreateStream(System.String,System.Boolean)~System.IntPtr")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration",              Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.Core.FMODSoundSystem.GetChannelFrequency(System.UInt32)~System.Single")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration",              Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.Core.FMODSoundSystem.GetChannelPan(System.UInt32)~System.Single")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration",              Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.Core.FMODSoundSystem.GetChannelPaused(System.UInt32)~System.Boolean")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration",              Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.Core.FMODSoundSystem.GetChannelVolume(System.UInt32)~System.Single")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration",              Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.Core.FMODSoundSystem.LoadSound(System.String,System.Boolean)~System.IntPtr")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration",              Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.Core.FMODSoundSystem.PlaySound(System.IntPtr,System.UInt32,System.Boolean)~System.UInt32")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration",              Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.Core.FMODSoundSystem.PlaySound(System.IntPtr,System.UInt32,System.Boolean,System.Single,System.Single)~System.UInt32")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration",              Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.EasyDraw.Text(System.String,System.Single,System.Single)")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration",              Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.Settings.ReadSettingsFromFile")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.Core.Texture2D.destroyGLTexture")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Core.Texture2D.bitmap")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Core.Texture2D.filename")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Core.Texture2D.height")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Core.Texture2D.width")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Core.Texture2D.wrap")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Transformable.matrix")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Transformable.Rotation")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Transformable.scale")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Transformable.scaleX")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Transformable.scaleY")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Window.centerX")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Window.centerY")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Window.height")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Window.width")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Window.windowX")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Window.windowY")]
[assembly: SuppressMessage("Style", "IDE0031:Use null propagation",                     Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.GameObject.Destroy")]
[assembly: SuppressMessage("Style", "IDE0031:Use null propagation",                     Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.Sprite.OnDestroy")]
[assembly: SuppressMessage("Style", "IDE0031:Use null propagation",                     Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.Sprite.RenderSelf(GXPEngine.Core.GLContext)")]
[assembly: SuppressMessage("Style", "IDE0031:Use null propagation",                     Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.SpriteBatch.RenderSelf(GXPEngine.Core.GLContext)")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization",           Justification = "<Pending>", Scope = "member", Target = "~M:TiledMapParser.TiledLoader.LoadImageLayer(System.Int32)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Transformable.x")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles",                            Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Transformable.y")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier",                    Justification = "<Pending>", Scope = "member", Target = "~F:TiledMapParser.TiledLoader._callingAssembly")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier",                    Justification = "<Pending>", Scope = "member", Target = "~F:TiledMapParser.TiledLoader._foldername")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier",                    Justification = "<Pending>", Scope = "member", Target = "~F:TiledMapParser.TiledLoader._manualObjects")]
[assembly: SuppressMessage("Style", "IDE1005:Delegate invocation can be simplified.",   Justification = "<Pending>", Scope = "member", Target = "~M:TiledMapParser.TiledLoader.LoadObjectGroup(System.Int32,System.Boolean)")]
[assembly: SuppressMessage("Style", "IDE0019:Use pattern matching",                     Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.Core.Texture2D.GetInstance(System.String,System.Boolean)~GXPEngine.Core.Texture2D")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier",                    Justification = "<Pending>", Scope = "member", Target = "~F:GXPEngine.Core.Texture2D.LoadCache")]
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members",		Justification = "<Pending>", Scope = "member", Target = "~M:MyGame.Update")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.Transformable.TransformDirection(System.Single,System.Single)~Vector2")]
[assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.Transformable.TransformPoint(System.Single,System.Single)~Vector2")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:GXPEngine.GameObject._children")]
[assembly: SuppressMessage("Style", "IDE0044:Add readonly modifier", Justification = "<Pending>", Scope = "member", Target = "~F:GXPEngine.GameObject._collider")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.GameObject.addChild(GXPEngine.GameObject)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.GameObject.createCollider~GXPEngine.Core.Collider")]
[assembly: SuppressMessage("Style", "IDE0038:Use pattern matching", Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.GameObject.FindObjectOfType``1~``0")]
[assembly: SuppressMessage("Style", "IDE0038:Use pattern matching", Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.GameObject.FindObjectsOfType``1(System.Collections.Generic.List{``0})")]
[assembly: SuppressMessage("Style", "IDE0018:Inline variable declaration", Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.GameObject.MoveUntilCollision(System.Single,System.Single,System.Collections.Generic.IEnumerable{GXPEngine.GameObject})~GXPEngine.Core.Collision")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.GameObject.removeChild(GXPEngine.GameObject)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.GameObject.collider")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.GameObject.game")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.GameObject.parent")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Transformable.rotation")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Input.mousePos")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Input.mouseX")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Input.mouseY")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.Sprite.initializeFromTexture(GXPEngine.Core.Texture2D)")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~M:GXPEngine.Sprite.setUVs")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Sprite.alpha")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Sprite.color")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Sprite.height")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Sprite.texture")]
[assembly: SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>", Scope = "member", Target = "~P:GXPEngine.Sprite.width")]
